#ChIP-seq analysis and peak calling analysis using DeepTools and MACS3
#For ChIP-seq use the package DeepTools.
# Since only one replicate is used, some analysis will not be possible, however, the comand lines are indicated.

# Intall MACS3 if not installed yet. Deeptools was installed before in the bio_tools conda environment.

conda install -n bio_tools -c bioconda macs3

# Create output directory for bamcompare results
mkdir -p results/chipseq/bamcomp
mkdir -p results/chipseq/fingerprint
#mkdir -p results/chipseq/multibams
#mkdir -p results/chipseq/plotcorr   
mkdir -p results/chipseq/macs

#Run bamcompare to compare ChIP vs Input samples; input files are aligned reads, i.e., sorted.bam. Keep the index sorted.bam.bai files in the same folder!
#Run each biological replicate data separatelly, then run again with replicates to make sure each replicate is reproducible.
#The bigwig file can be opened in IGV for visualization: https://igv.org/
#It is also useful to repeat the analysis below outputing "bedgraph" format.

# datsaet
# RAP1 ChIP-seq, Touray et al. 2023, eLife, https://doi.org/10.7554/eLife.89331.4

# Run bamCompare for biological replicate 1:
bamCompare -b1 dataset/chipseq/rap1-chip-B3_sorted.bam -b2 dataset/chipseq/rap1-inp-B4_sorted.bam \
 --outFileName results/chipseq/bamcomp/chip-inp-bpm.bw \
 --normalizeUsing BPM --extendReads 720 \
 --scaleFactorsMethod None \
 --binSize 50 --smoothLength 60 --centerReads \
 --outFileFormat bigwig --numberOfProcessors 6

#Check overall enrichment of ChIP with plotFingerprint:
  plotFingerprint --bamfiles dataset/chipseq/rap1-chip-B3_sorted.bam -b2 dataset/chipseq/rap1-inp-B4_sorted.bam \
 --labels chip_bio1 Inp_bio1 \
 --extendReads 600  --binSize=1000 \
 --plotFile results/chipseq/fingerprint/ChIPvsInput_bio1.fingerprint.pdf \
 --outRawCounts results/chipseq/fingerprint/ChIPvsInput_bio1_coverage.tab \
 --numberOfProcessors 6

# Compare biological replicates using multiBamSummary and plotCorrelation analysis:
#multiBamSummary bins --bamfiles Input_Bio1_sorted.bam ChIP_Bio1_sorted.bam #Input_Bio2_sorted.bam ChIP_Bio2_sorted.bam Input_Bio3_sorted.bam ChIP_Bio3_sorted.bam \
# --outFileName results/chipseq/multibams/multiBamArray_Inp-vs-ChIP-Bio1-3.npz #--binSize=5000 \
# --extendReads=1000 --labels InputBio1 ChIP-Bio1 InputBio2 ChIP-Bio2 InputBio3 ChIP-Bio3 \
# --numberOfProcessors 6 \

# plotCorrelation --corData results/chipseq/multibams/multiBamArray_Inp-vs-ChIP-Bio1-3.npz \
# --plotFile results/chipseq/plotcorr/REST_bam_correlation_bin.pdf \
# --outFileCorMatrix results/chipseq/plotcorr/corr_matrix_bin.txt \
# --whatToPlot heatmap --corMethod spearman \

#MACS3 analysis for broad peak calling:
#Use bedtools to convert bam to bed files using bedtools (do the same to all replicates):
bedtools bamtobed -i dataset/chipseq/rap1-chip-B3_sorted.bam > results/chipseq/macs/rap1-chip-B3_sorted.bed
bedtools bamtobed -i dataset/chipseq/rap1-inp-B4_sorted.bam > results/chipseq/macs/rap1-inp-B4_sorted.bed

# Run MACS3 for peak calling using broad peak paramters. You can change the parameters as needed
macs3 callpeak -t results/chipseq/macs/rap1-chip-B3_sorted.bed \
 -c results/chipseq/macs/rap1-inp-B4_sorted.bed \
 -f BED -g 35000000 -n chip-rap1-macs3 --nomodel --extsize 500 --fix-bimodal \
 --broad --broad-cutoff 0.05 --outdir results/chipseq/macs/
 
 # Visualize your data using IGV or pyGenomeTracks. You can also use the bigwig files generated by bamCompare for visualization.
